# Generated by Django 4.1 on 2022-12-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bidders_delete_bids_delete_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='user',
        ),
    ]
