# Generated by Django 4.1 on 2022-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_auctionlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidders',
            name='list_id',
            field=models.IntegerField(),
        ),
    ]
