# Generated by Django 4.1 on 2022-12-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bidders_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidders',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
